### ISSUE TITLE
Create helper methods to port TCL based Integration Tests from Redis 7.2.5

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#138]

**Comment by AshwinKul28** [comment]
Once [this](https://github.com/DiceDB/dice/pull/211) gets merged, I would like to work on it of this is still valid, and would like to understand more on the requirement. @arpitbbhayani

**Comment by AshwinKul28** [comment]
HI @JyotinderSingh Can you please assign this to me?

**Comment by JyotinderSingh** [comment]
> HI @JyotinderSingh Can you please assign this to me?

Assigned

**Comment by AshwinKul28** [comment]
One helper website: https://www.codeconvert.ai/tcl-to-golang-converter

**Comment by AshwinKul28** [comment]
Work done till now:

Changes made in the executeCommand function
```go
    // For running redis tests
    if cmd.Cmd == "SELECT" || cmd.Cmd == "FUNCTION" ||
        cmd.Cmd == "FLUSHALL" || cmd.Cmd == "CONFIG" ||
        cmd.Cmd == "RPUSH" || cmd.Cmd == "HSET" ||
        cmd.Cmd == "LRANGE" || cmd.Cmd == "ACL" ||
        cmd.Cmd == "FLUSHDB" || cmd.Cmd == "SCAN" ||
        cmd.Cmd == "SCARD" || cmd.Cmd == "ZCARD" {
        return RespOK
    }
```

The above commands are skipped because not implemented in the dice. 

Command to run tests from Redis:
```sh
$ /runtest --host 127.0.0.1 --port 7379 --tags -needs:debug --tags -cluster:skip
```

It automatically skips those tests that have the tag -external:skip when running on an external server. We will see what to do about those tests. 

[just a basic run. Now, I will dig deeper into it 🙂]

[redis-tcl-integration-report.txt](https://github.com/user-attachments/files/16677335/redis-tcl-integration-report.txt)

Many tests failed, but many passed

**Comment by AshwinKul28** [comment]
Still working on it :)

**Comment by lucifercr07** [comment]
@AshwinKul28 would like to contribute along the same, please let me know if we can split tasks.

**Comment by lucifercr07** [comment]
Initial integration test framework has been merged as part of [this](https://github.com/DiceDB/dice/pull/435) PR.
Follow up unit tests would be taken care as part of below issues, hence closing this one.
https://github.com/DiceDB/dice/issues/448
https://github.com/DiceDB/dice/issues/449
