### ISSUE TITLE
Getting an expired key hangs the server

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#201]
I am using the DiceDB server on my local machine and connecting it with the DiceDB CLI.
I set the key with some expiry and when I keep getting the key, the server hangs after that expiration time.

**How to reproduce**

1. Start DiceDB Server
2. Connect to the server using DiceDB CLI
3. fire command `SET mykey "Hello, World!" EX 10`
4. fire command `GET mykey`
5. fire command `GET mykey`
6. fire command `GET mykey`
7. ...

Keep firing the command for few seconds. After `10` seconds you will see that the client and server hanged. `CTRL+C` on CLI, kills the CLI, but the server remains in the blocked state.

The DiceDB server is now unresponsive. Even after hitting `CTRL+C` it does not exit.
The only way to shut down the process is by identifying the process listening to this port and killing it.

```
$ sudo netstat -atlpn | grep :7379
$ sudo kill -9 <process_id>
```

![image](https://github.com/user-attachments/assets/4760621f-fffd-409e-a5d8-ea53320d0ecc)

**Comment by apoorvyadav1111** [comment]
Hi, I think the issue is due to mutexes. In Get, we are acquiring both mutexes. But when a key is expired we are releasing only storeMutex. In Del func, we need to acquire both mutexes but the keypoolMutex was not unlocked before calling Del(k). I have tried the code in local by releasing both mutexes before calling Del(k) and it works. If this is actually the reason, I'll be glad to create a PR.
<img width="348" alt="image" src="https://github.com/user-attachments/assets/db9733b9-26bc-44b6-8e64-4b888ca75538">

**Comment by arpitbbhayani** [comment]
@apoorvyadav1111 Go ahead and raise the PR. @JyotinderSingh recently added pessimistic locks.

@JyotinderSingh FYI, you need to review this :)

**Comment by apoorvyadav1111** [comment]
PR raised for this issue: https://github.com/DiceDB/dice/pull/209
