### ISSUE TITLE
Address thread safety for int dencoding

### ISSUE THREAD

**Issue by JyotinderSingh** [DiceDB/dice#223]
There's an existing TODO comment about thread safety for the global 'buf' variable. We need to address this to ensure the dencoding utils are safe for concurrent use.

## Requirements
- Consider using a sync.Pool
- Update tests to verify thread safety (add concurrent encoding tests)
- benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by kushal0511-not** [comment]
@JyotinderSingh i would like to work this. Can you assign this to me?

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh i would like to work this. Can you assign this to me?
> 
> 

Assigned

**Comment by arpitbbhayani** [comment]
@kushal0511-not Go for it.

It would be awesome if you keep posting updates to this issue so that we know you are working on it. If we see an inactivity of 7 days, we will remove your assignment. This is just to ensure that the project maintains its momentum and others are not blocked on this work.

But it really means a ton to us that you are contributing to this project. Thanks again.
