### ISSUE TITLE
Fix Flakey Test - COPY with JSON simple JSON

### ISSUE THREAD

**Issue by yashs360** [DiceDB/dice#356]
COPY with JSON simple JSON is flakey due to order of output. Review and fix flakeyness. `copy_test.go`

**Comment by VedWhat** [comment]
Is this really a test issue? One thing I noticed is the code path 

```
127.0.0.1:7379> JSON.SET k1 $ '{"name":"John","age":30,"b": "c"}'
"OK"
127.0.0.1:7379> JSON.SET k1 $ '{"name":"John","age":30,"b": "c"}'
"OK"
127.0.0.1:7379> copy k1 k2
(integer) 1
127.0.0.1:7379> json.get k2
"{\"b\":\"c\",\"name\":\"John\",\"age\":30}"
127.0.0.1:7379> json.get k2
"{\"name\":\"John\",\"age\":30,\"b\":\"c\"}"
127.0.0.1:7379>
```

on subsequent json.gets without any change the ordering is different. Will look into this further, let me know if I'm missing something

**Comment by VedWhat** [comment]
Okay I think I get what's happening, due to sonic.marshal not ordering keys by default (did not know this) we get the out of order JSON objects. In our usecase since order doesn't matter anyway, this should be okay.

I think it makes sense to fix the test then to just expect an ordered JSON and keep both expected and sent JSON ordered.

Can make this change let me know @yashs360
