### ISSUE TITLE
Add support for command `JSON.RESP`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#500]
Add support for the `JSON.RESP` command in DiceDB similar to the [`JSON.RESP` command in Redis](https://redis.io/docs/latest/commands/command-list/). Please refer to the following commit in Redis to understand the implementation specifics - [source](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa).

Write unit and integration tests for the command referring to the tests written in the [Redis codebase 7.2.5](https://github.com/redis/redis/tree/f60370ce28b946c1146dcea77c9c399d39601aaa). For integration tests, you can refer to the `tests` folder. Note: they have used `TCL` for the test suite, and we need to port that to our way of writing integration tests using the relevant helper methods. Please refer to our [tests directory](https://github.com/DiceDB/dice/tree/master/tests).

For the command, benchmark the code and measure the time taken and memory allocs using [`benchmem`](https://blog.logrocket.com/benchmarking-golang-improve-function-performance/) and try to keep them to the bare minimum.

**Comment by lbihani9** [comment]
@arpitbbhayani I'd like to work on this task. Can you please assign this to me?

**Comment by lucifercr07** [comment]
@lbihani9 assigned, thanks for picking this up.

**Comment by lbihani9** [comment]
@lucifercr07 I've completed the implementation, but without using jsonpath because other JSON commands are also not using it. Do we want to add support for jsonpath in `JSON.RESP` command?

Updates so far:
1. Our dice cli probably has some issue (screencast added below). Spent too much time figuring out why it wasn't working as expected, then switched to redis cli and it started working correctly. 🫠

https://github.com/user-attachments/assets/558ce18d-1a90-4434-b28e-d4b5179e5857

<img width="1504" alt="Screenshot 2024-09-11 at 6 48 03 PM" src="https://github.com/user-attachments/assets/e0b75c2a-3bac-4c57-95de-ff59f3fb5034">

2. I didn't find testcases for `JSON.RESP` in main redis repository (link shared above) maybe because JSON data structure is a part of redis-stack and not regular redis. I'm supposed to add unit and integration tests for this command, right?

PS: I'm not well versed with unit and integration tests so it might take me sometime. I hope this won't be a blocker. 😅

**Comment by psrvere** [comment]
@JyotinderSingh - Can I work on this?

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh - Can I work on this?

Assigned

**Comment by psrvere** [comment]
@JyotinderSingh - Please review PR #631
