### ISSUE TITLE
Add support for `QUEUEINT`

### ISSUE THREAD

**Issue by arpitbbhayani** [DiceDB/dice#68]
To power Milestone 1: Pokemon Premier League #46, we need to support the queue data structure. We start with an integer queue that needs to have very optimal on space and time. Also, add tests to ensure the correctness of the system.

Commands Specification: https://github.com/DiceDB/dice/wiki/Queue-of-Integers

**Comment by zeu5** [comment]
Not to dig up old graves. But I wanted a simple first issue to start working on this repo. Turns out this is a bit confusing for me.

The current queue implementation is slower and less efficient in time and space than the most basic queue implementation. Maybe I'm missing something fundamental here. Raised a PR with benchmarks to test - #130 

Happy to take feedback.
