### ISSUE TITLE
Bug: Flaky test in HVALS integration tests

### ISSUE THREAD

**Issue by apoorvyadav1111** [DiceDB/dice#748]
Hi team,

one of the recent merges for a new feature has flaky tests, leading to failing GitHub action run indeterministically. Please check the log below:
![image](https://github.com/user-attachments/assets/74f2b1db-840a-40d5-b019-aee7144c13b9)

this change was introduced in PR: https://github.com/DiceDB/dice/pull/710

In addition to the flaky test, adding names to the test cases will help future contributors.

Thanks

**Comment by ayushsatyam146** [comment]
I can take this up @apoorvyadav1111 @lucifercr07 @JyotinderSingh

**Comment by JyotinderSingh** [comment]
> I can take this up @apoorvyadav1111 @lucifercr07 @JyotinderSingh 

I think I've already fixed this in a recent commit. Can you please investigate if the problem still persists?
If yes please take it up, if not we can close this. Either way, please let us know here what the current situation is.

**Comment by ayushsatyam146** [comment]
Sure I will update here with my findings

**Comment by JyotinderSingh** [comment]
> @JyotinderSingh can you assign this one to me? It's easier for me to track that way

We've implemented a temporary fix for this by only limiting the result to one field (so that the ordering doesn't affect the result) in the unit test.

We still check complete results with order ignored in the integration tests so the test coverage has not suffered.

Feel free to improve the unit test though to make it more robust.

**Comment by ayushsatyam146** [comment]
Hi @JyotinderSingh I went through the tests written for `HVALS` and I think the command has good test coverage combined across unit and integration tests. I can add a unit test for unordered results for multiple fields but that would be a repetition since it's already covered in integration tests. 
If you feel like we can add some other checks then I will add them to the unit tests otherwise we are good to close this one. Thanks!
